FROM node:22-alpine

WORKDIR /app

COPY package.json ./
COPY apps/web/package.json ./apps/web/
COPY packages/shared/package.json ./packages/shared/

RUN npm install

COPY packages/shared ./packages/shared
COPY apps/web ./apps/web

RUN npm run build -w @quizzeira/shared

WORKDIR /app/apps/web

EXPOSE 5173

CMD ["sh", "-c", "npm run dev -w @quizzeira/shared & npm run dev --workspace=@quizzeira/web -- --host 0.0.0.0"]
