FROM node:22-alpine

WORKDIR /app

COPY package.json ./
COPY apps/question-generator/package.json ./apps/question-generator/
COPY packages/shared/package.json ./packages/shared/
COPY packages/worker-kit/package.json ./packages/worker-kit/

RUN npm install

COPY packages/shared ./packages/shared
COPY packages/worker-kit ./packages/worker-kit
COPY apps/question-generator ./apps/question-generator

RUN npm run build -w @quizzeira/shared

WORKDIR /app/apps/question-generator

CMD ["npm", "run", "dev"]
