import type { GeneratedQuestionInput } from "@quizzeira/shared";

export type SeedBankQuestion = GeneratedQuestionInput & { subject: string };

/** Transpetro PSP Terra Superior 2023.2 — Administração caderno + gabarito oficial.
 * Sources: administracao.pdf + gabarito.pdf (PCI Concursos / Cesgranrio).
 */
export const TRANSPETRO_ADMIN_2023_SEED: SeedBankQuestion[] = [
  {
    type: "MULTIPLE_CHOICE",
    subject: "Língua Portuguesa",
    prompt: "O fragmento de abertura da crônica “Estou me vendo debaixo de uma árvore, lendo a pequena história da literatura brasileira.” (parágrafo 1) faz referência a uma",
    options: ["previsão", "fantasia", "esperança", "expectativa", "reminiscência"],
    correctIndex: 4,
    referenceAnswer: null,
    explanation: "Gabarito oficial Cesgranrio — Transpetro/PSP/TERRA/NÍVEL SUPERIOR 2023.2 (Administração). Fonte pública via PCI Concursos.",
  },
  {
    type: "MULTIPLE_CHOICE",
    subject: "Língua Portuguesa",
    prompt: "No texto, as palavras que marcam o sentimento de insegurança vivenciado pela narradora ao conversar com seu pai são:",
    options: ["confissão (parágrafo 7) e andar (parágrafo 8)", "rodeios (parágrafo 4) e gaguejar (parágrafo 6)", "cabecinha (parágrafo 7) e mudar (parágrafo 8)", "sepultura (parágrafo 3) e renegar (parágrafo 7)", "severidade (parágrafo 7) e esquecer (parágrafo 5)"],
    correctIndex: 1,
    referenceAnswer: null,
    explanation: "Gabarito oficial Cesgranrio — Transpetro/PSP/TERRA/NÍVEL SUPERIOR 2023.2 (Administração). Fonte pública via PCI Concursos.",
  },
  {
    type: "MULTIPLE_CHOICE",
    subject: "Língua Portuguesa",
    prompt: "De acordo com o texto, na opinião do pai, a filha deveria",
    options: ["aprender a língua da avó.", "valorizar a língua materna.", "escrever em idiomas diversos.", "ler outros poemas de Olavo Bilac.", "estudar história da literatura brasileira."],
    correctIndex: 1,
    referenceAnswer: null,
    explanation: "Gabarito oficial Cesgranrio — Transpetro/PSP/TERRA/NÍVEL SUPERIOR 2023.2 (Administração). Fonte pública via PCI Concursos.",
  },
  {
    type: "MULTIPLE_CHOICE",
    subject: "Língua Portuguesa",
    prompt: "Ao ler os versos de Olavo Bilac, o “quase” susto da narradora, mencionado no parágrafo 2, foi motivado pela",
    options: ["possibilidade de seus escritos não serem conhecidos.", "falta de conhecimento sobre a localização do Lácio.", "necessidade de aprender uma língua diferente.", "surpresa com a postura pessimista do poeta.", "abordagem da temática da morte."],
    correctIndex: 0,
    referenceAnswer: null,
    explanation: "Gabarito oficial Cesgranrio — Transpetro/PSP/TERRA/NÍVEL SUPERIOR 2023.2 (Administração). Fonte pública via PCI Concursos.",
  },
  {
    type: "MULTIPLE_CHOICE",
    subject: "Língua Portuguesa",
    prompt: "A palavra que funciona como um mecanismo de coesão textual, retomando um antecedente, em:",
    options: ["firmeza", "rispidez", "discrição", "desgosto", "incompreensão"],
    correctIndex: 2,
    referenceAnswer: null,
    explanation: "Gabarito oficial Cesgranrio — Transpetro/PSP/TERRA/NÍVEL SUPERIOR 2023.2 (Administração). Fonte pública via PCI Concursos.",
  },
  {
    type: "MULTIPLE_CHOICE",
    subject: "Língua Portuguesa",
    prompt: "A frase em que as vírgulas estão empregadas com a mesma função que em “Não esquecer que a minha avó, Pedrina Perucchi, era italiana” (parágrafo 5) é:",
    options: ["escrever seus contos em outra língua.", "escrevera seus contos em outra língua.", "tiver escrito seus contos em outra língua.", "teria escrito seus contos em outra língua.", "tivesse escrito seus contos em outra língua. SC A R O H N U SC N U"],
    correctIndex: 3,
    referenceAnswer: null,
    explanation: "Gabarito oficial Cesgranrio — Transpetro/PSP/TERRA/NÍVEL SUPERIOR 2023.2 (Administração). Fonte pública via PCI Concursos.",
  },
  {
    type: "MULTIPLE_CHOICE",
    subject: "Língua Portuguesa",
    prompt: "No parágrafo 6, “nossa língua é sepultura mesmo, tudo o que a gente fizer vai para debaixo da terra, desaparece!”, o segmento em destaque pode articular-se com o segmento anterior, sem alteração do sentido original, empregando-se o conector",
    options: ["em língua portuguesa", "com a língua portuguesa", "para a língua portuguesa", "sobre a língua portuguesa", "por causa da língua portuguesa"],
    correctIndex: 1,
    referenceAnswer: null,
    explanation: "Gabarito oficial Cesgranrio — Transpetro/PSP/TERRA/NÍVEL SUPERIOR 2023.2 (Administração). Fonte pública via PCI Concursos.",
  },
  {
    type: "MULTIPLE_CHOICE",
    subject: "Administração",
    prompt: "A fim de melhorar a eficácia das respostas de uma empresa de transporte marítimo em situações de emergência, foi implementado um sistema de apoio à decisão (SAD). Diferentemente do sistema de informações gerenciais (SIG), o SAD, no que diz respeito à(ao)",
    options: ["apoio à decisão, oferece informações sobre o desempenho da organização, em vez de informações e técnicas de apoio à decisão para analisar problemas ou oportunidades específicos.", "formato das informações, possui um formato pré-especificado fixo, em vez de um formato ad hoc, flexível e adaptável.", "metodologia de processamento das informações, possui informações produzidas por modelagem analítica de dados dos negócios, em vez de informações produzidas por extração e manipulação de dados dos negócios.", "forma e à frequência das informações, apresenta informações periódicas, de exceção, por demanda e relatórios e respostas em pilha, em vez de informações por consultas e respostas interativas.", "ambiente operacional, disponibiliza informações em um ambiente fácil e direto para que os executivos da empresa possam rapidamente obter uma informação, em vez de pacotes de aplicações empresariais."],
    correctIndex: 2,
    referenceAnswer: null,
    explanation: "Gabarito oficial Cesgranrio — Transpetro/PSP/TERRA/NÍVEL SUPERIOR 2023.2 (Administração). Fonte pública via PCI Concursos.",
  },
  {
    type: "MULTIPLE_CHOICE",
    subject: "Administração",
    prompt: "A Transpetro assumiu o desafio de projetar e instalar, em menos de um ano, os sistemas de injeção de biodiesel em seus terminais com carregamento rodoviário. A estratégia para implementar o projeto foi adotar um plano de ação com visão matricial, na qual o coordenador do projeto pudesse gerenciar todas as informações das várias áreas envolvidas. Por ser um projeto com características multidisciplinares, o trabalho e a colaboração da equipe tornaram-se fatores críticos de sucesso. Para tanto, formaram-se equipes autogerenciadas constituídas por grupos de funcionários que",
    options: ["eram do mesmo nível hierárquico, mas de diferentes setores da empresa e que se juntaram para cumprir uma tarefa.", "realizavam trabalhos muito relacionados ou interdependentes e que assumiram muitas das responsabilidades que antes eram de seus antigos supervisores.", "eram do mesmo departamento e que se reuniram algumas horas por semana para discutir formas de melhorar a qualidade, a eficiência e o ambiente de trabalho.", "usaram a tecnologia da informática para reunir seus membros, fisicamente dispersos, e permitir que eles atingissem um objetivo comum.", "apresentaram espírito de equipe e folga social elevados, estimulando o esforço individual e aumentando a produtividade geral. PROVA 1 - ADMINISTRAÇÃO 6 TERRA www.pciconcursos.com.br pcimarkpci MjgwNDozZmJjOjBhODA6MTMwMDo1MDI0OjUwZmY6MjZiNTo2M2Y3:VHVlLCAwOCBTZXAgMjAyNiAxNTowMjoyNiAtMDMwMA== TRANSPETRO"],
    correctIndex: 1,
    referenceAnswer: null,
    explanation: "Gabarito oficial Cesgranrio — Transpetro/PSP/TERRA/NÍVEL SUPERIOR 2023.2 (Administração). Fonte pública via PCI Concursos.",
  },
  {
    type: "MULTIPLE_CHOICE",
    subject: "Administração",
    prompt: "Compreender os sistemas de informação, no que diz respeito às suas atividades, aumenta as chances de sucesso na sua implementação e implantação, além de facilitar na definição dos papéis e posturas dos atores de todo o ambiente organizacional. Os sistemas de informação permitem cinco atividades, que são as seguintes:",
    options: ["a utilização em si; os benefícios oferecidos; a contribuição para o desempenho empresarial; a governança e administração de TI; o papel dos executivos.", "os recursos de software; os recursos de hardware; os recursos de rede; os recursos de dados; os recursos humanos.", "a coleta; o armazenamento; o processamento; a recuperação; a disseminação de informações.", "a informação contábil; a informação financeira; a informação industrial; a informação de marketing; a informação da gestão de recursos humanos.", "o suporte inteligente; o apoio a grupos e a decisões; a automação de escritório; a administração do conhecimento; o processamento de transações."],
    correctIndex: 2,
    referenceAnswer: null,
    explanation: "Gabarito oficial Cesgranrio — Transpetro/PSP/TERRA/NÍVEL SUPERIOR 2023.2 (Administração). Fonte pública via PCI Concursos.",
  },
  {
    type: "MULTIPLE_CHOICE",
    subject: "Administração",
    prompt: "Sistemas de informações na gestão de pessoas disponibilizam diferentes tipos de dados, que podem ser classificados segundo categorias diversas. Os dados sobre a expectativa das pessoas e planos de desenvolvimento referem-se a",
    options: ["registros inseridos pelas pessoas, com supervisão de suas chefias, com informações históricas que relatam desejos e necessidades dos indivíduos e seus planos individuais de ascensão vertical ou a movimentação lateral, sendo usados pela organização para conciliação de expectativas.", "insumos resultantes do processo de avaliação com pessoas internas, que apresenta informações sobre resultados obtidos, desenvolvimento e comportamento, e avaliações colegiadas sobre potencial e possibilidades de desenvolvimento, sendo usados pela organização para avaliar relacionamento com as chefias.", "insumos resultantes de processo de avaliação realizados por entidades ou profissionais especializados, de modo a complementar as informações referentes ao potencial para ocupar posições críticas para a organização, sendo usados pela organização para reflexão sobre a carreira.", "informações pessoais, biografia profissional, posições ocupadas na organização, ações de desenvolvimento pelas quais a pessoa passou, projetos em que atuou, formação pessoal e profissional, sendo usados pela organização para recrutamento interno.", "ausências, afastamentos, viagens realizadas a trabalho, acidentes de trabalho em que a pessoa esteve envolvida, sendo usados pela organização para processo sucessório e movimentação interna."],
    correctIndex: 0,
    referenceAnswer: null,
    explanation: "Gabarito oficial Cesgranrio — Transpetro/PSP/TERRA/NÍVEL SUPERIOR 2023.2 (Administração). Fonte pública via PCI Concursos.",
  },
  {
    type: "MULTIPLE_CHOICE",
    subject: "Administração",
    prompt: "Em organizações grandes e complexas, cada área desenvolve um nível de tecnologia com diferentes graus de excepcionalidade e capacidade de análise, devendo a estrutura da organização ser ajustada para atender às necessidades dessa tecnologia. Dependendo do tipo de tecnologia da área, esta seguirá um modelo mais burocrático ou orgânico em termos de formalização, centralização, qualificação de pessoal, abrangência do controle e comunicação. Portanto, tem-se que a tecnologia",
    options: ["emergentes", "maduras", "decadentes", "sustentáveis", "fragmentadas"],
    correctIndex: 3,
    referenceAnswer: null,
    explanation: "Gabarito oficial Cesgranrio — Transpetro/PSP/TERRA/NÍVEL SUPERIOR 2023.2 (Administração). Fonte pública via PCI Concursos.",
  },
  {
    type: "MULTIPLE_CHOICE",
    subject: "Administração",
    prompt: "Tomadores de decisão que fazem uso de um estilo voltado para a intuição se concentram em desenvolver abstrações e exemplos figurativos para que sejam utilizados na tomada de decisão, com ênfase na imaginação e nas possibilidades. Esse estilo voltado para a intuição pode mostrar-se valioso em situações específicas, quando há",
    options: ["um baixo nível de ambiguidade e várias alternativas de solução plausíveis, com bons argumentos para cada uma delas.", "fatos ilimitados que indicam claramente o caminho a ser seguido.", "tempo ilimitado e muitos precedentes que não favorecem decisões inovadoras e criativas.", "várias alternativas de soluções plausíveis, com bons argumentos para cada uma delas.", "um problema estruturado e uma situação com alto nível de certeza. TERRA 7 PROVA 1 - ADMINISTRAÇÃO www.pciconcursos.com.br pcimarkpci MjgwNDozZmJjOjBhODA6MTMwMDo1MDI0OjUwZmY6MjZiNTo2M2Y3:VHVlLCAwOCBTZXAgMjAyNiAxNTowMjoyNiAtMDMwMA== TRANSPETRO"],
    correctIndex: 3,
    referenceAnswer: null,
    explanation: "Gabarito oficial Cesgranrio — Transpetro/PSP/TERRA/NÍVEL SUPERIOR 2023.2 (Administração). Fonte pública via PCI Concursos.",
  },
  {
    type: "MULTIPLE_CHOICE",
    subject: "Administração",
    prompt: "Uma empresa de navegação optou pela operação Ship to Ship (STS), com base numa informação inicial de que a eficiência aumentaria. Essa decisão foi afetada pelo viés de ancoragem, que é a tendência a um indivíduo",
    options: ["buscar informações que corroborem escolhas anteriores e descartar as que contestem julgamentos prévios.", "acreditar que é possível prever o resultado de eventos aleatórios, favorecendo o controle e a gestão do acaso.", "preferir um ganho certo de uma quantidade moderada a um resultado mais arriscado, mesmo que este tenha uma compensação mais alta.", "julgar as coisas com base nas informações mais facilmente disponíveis, levando a superestimar eventos improváveis.", "fixar-se em uma informação como ponto de partida e a dificuldade de ajustar-se diante de informações posteriores."],
    correctIndex: 4,
    referenceAnswer: null,
    explanation: "Gabarito oficial Cesgranrio — Transpetro/PSP/TERRA/NÍVEL SUPERIOR 2023.2 (Administração). Fonte pública via PCI Concursos.",
  },
  {
    type: "MULTIPLE_CHOICE",
    subject: "Administração",
    prompt: "A maioria dos administradores afirma estar frustrada com os sistemas de avaliação de desempenho, que falham ao identificar as mudanças que os funcionários necessitam fazer. Os funcionários se apegam às observações que recebem do gestor, considerando possíveis implicações em sua remuneração e promoção, e não ouvem o que é dito a eles, sobre os aspectos que precisam mudar e como desenvolver competências. Para resolver esse desafio, foi criado um processo para prover os gestores (e também outros níveis, como o de especialistas) de informações sobre como seu superior, pares e funcionários os veem no trabalho. Esse processo é denominado avaliação de desempenho em",
    options: ["três dimensões ou feedback 360o", "listas de verificação de comportamentos, descrições ou adjetivos", "escalas de classificação de conhecimento e qualidades pessoais", "figuras do “surfar supérfluo” ou observação física", "incidentes críticos e frases comportamentais"],
    correctIndex: 0,
    referenceAnswer: null,
    explanation: "Gabarito oficial Cesgranrio — Transpetro/PSP/TERRA/NÍVEL SUPERIOR 2023.2 (Administração). Fonte pública via PCI Concursos.",
  },
  {
    type: "MULTIPLE_CHOICE",
    subject: "Administração",
    prompt: "Um gerente está tentando decidir se deve construir um novo navio pequeno ou grande. A decisão depende muito da demanda futura que deverá surgir, que poderá ser baixa ou alta. O gerente pode fazer uma relação dos possíveis eventos, mas não pode estimar suas probabilidades, portanto, há uma tomada de decisão com incerteza. Nesse caso, o gerente opta por uma regra de decisão denominada “Laplace”, escolhendo a seguinte alternativa:",
    options: ["fará com que seu custo total seja menor do que o de seus concorrentes, e continue auferindo lucros, mesmo quando vários de seus concorrentes já tiveram seus lucros consumidos na competição.", "será capaz de atender ao seu alvo estratégico com mais eficiência do que seus concorrentes que buscam toda a indústria ou muitos segmentos.", "oferecerá um produto considerado único por seus clientes, isto é, cujas características o distinguem daqueles oferecidos pela concorrência.", "oferecerá, em nível de paridade de preço e custo, um produto melhor que o dos concorrentes, em termos de seus atributos técnicos, ou seja, melhor desempenho funcional, maior durabilidade ou maior confiabilidade.", "diferenciará seu produto, desenvolvendo por meio de propaganda e técnicas de promoção, uma imagem que o torne distinto dos demais. 8 TERRA www.pciconcursos.com.br pcimarkpci MjgwNDozZmJjOjBhODA6MTMwMDo1MDI0OjUwZmY6MjZiNTo2M2Y3:VHVlLCAwOCBTZXAgMjAyNiAxNTowMjoyNiAtMDMwMA== TRANSPETRO"],
    correctIndex: 2,
    referenceAnswer: null,
    explanation: "Gabarito oficial Cesgranrio — Transpetro/PSP/TERRA/NÍVEL SUPERIOR 2023.2 (Administração). Fonte pública via PCI Concursos.",
  },
  {
    type: "MULTIPLE_CHOICE",
    subject: "Administração",
    prompt: "Considere o texto a seguir. Ludmilla dá o sangue A cantora Ludmilla prometeu dar um ingresso de seu show “Numanice” para cada pessoa que doasse sangue entre os dias 5 e 7 de julho, no Rio de Janeiro. Como resultado, recordes de doações foram batidos. Ao ver os números, eu pensei que este seria um belíssimo caso em que a economia comportamental pode explicar o fenômeno. Ela é uma disciplina que surge da incorporação, pela economia, de desenvolvimentos teóricos e descobertas empíricas no campo da psicologia, da neurociência e de outras ciência sociais. Um funcionário teve de resolver um conflito diante de uma situação de impasse, na qual era inviável alinhar as diferenças entre as partes por m",
    options: ["conciliador", "mediador", "consultor", "denunciante", "árbitro SANTANA, Irapuã. Ludmilla dá o sangue. O Globo, Rio de Janeiro, ano XCVIII, n. 32.851, 17 jul. 2023. Opinião, p. 3. Adaptado."],
    correctIndex: 4,
    referenceAnswer: null,
    explanation: "Gabarito oficial Cesgranrio — Transpetro/PSP/TERRA/NÍVEL SUPERIOR 2023.2 (Administração). Fonte pública via PCI Concursos.",
  },
  {
    type: "MULTIPLE_CHOICE",
    subject: "Administração",
    prompt: "A Transpetro e o Complexo Industrial e Portuário do Pecém criaram um grupo de trabalho, com apoio do governo do Ceará, para negociar uma solução para a continuidade do fornecimento de gás natural para a malha de gasodutos. Buscou-se um acordo que pudesse gerar uma solução ganha-ganha. Para o autor do texto, o sucesso da campanha da cantora Ludmilla explica-se pela tomada de decisão intuitiva que pode ser caracterizada como um",
    options: ["distributiva", "integrativa", "acidental", "acomodatícia", "imediata"],
    correctIndex: 1,
    referenceAnswer: null,
    explanation: "Gabarito oficial Cesgranrio — Transpetro/PSP/TERRA/NÍVEL SUPERIOR 2023.2 (Administração). Fonte pública via PCI Concursos.",
  },
  {
    type: "MULTIPLE_CHOICE",
    subject: "Administração",
    prompt: "Com a parceria consultiva da FGV Energia, a Transpetro consolidou um novo Plano Estratégico, no qual, além de iniciativas estratégicas voltadas diretamente aos negócios e aos clientes, formalizou a estratégia de transformação digital e inovação que perpassa toda a companhia. A empresa acredita que transformar digitalmente uma organização é pensar não só em termos operacionais, mas também promover uma cultura ágil no que tange à percepção sobre o que é valor para o mercado, estruturando a capacidade de antecipação e ação, em um mindset inovador. Com base nessas constatações, é possível afirmar que uma cultura adaptativa é caracterizada",
    options: ["pelo foco interno e pela orientação consistente para um ambiente estável, apoiando uma abordagem metódica de fazer negócios, seguindo políticas e práticas estabelecidas como meio de atingir as metas e obtendo sucesso devido ao alto grau de integração e eficiência.", "pela combinação de alto grau de risco no negócio com rápida velocidade de feedback, na qual se assumem altos riscos e se recebe um rápido feedback sobre suas ações, se possui uma; é orientação para o curto prazo com forte competição interna, gerando falta de cooperação entre os membros.", "por pressupostos de estabilidade e formalidade no processo informacional, na qual a documentação, as regras e os regulamentos são usados para a obtenção da estabilidade e continuidade da organização, que evita o risco e enfatiza prioritariamente os problemas operacionais.", "pela baixa sociabilidade e alta solidariedade, pelo foco na estratégia de vencer o mercado, por pessoas direcionadas por objetivos comuns, que, ao mesmo tempo são unidas por fortes laços sociais, alto grau de comprometimento nos resultados e na lealdade à organização.", "pela colocação do foco estratégico no ambiente externo através da flexibilidade e de mudanças para satisfazer as necessidades do cliente, encorajando valores de empreendedorismo, normas e crenças que sustentam a capacidade da organização em detectar, interpretar e traduzir sinais do ambiente em novos comportamentos reativos. TERRA"],
    correctIndex: 4,
    referenceAnswer: null,
    explanation: "Gabarito oficial Cesgranrio — Transpetro/PSP/TERRA/NÍVEL SUPERIOR 2023.2 (Administração). Fonte pública via PCI Concursos.",
  },
  {
    type: "MULTIPLE_CHOICE",
    subject: "Administração",
    prompt: "Em 2013, foi apresentada uma dissertação de mestrado em Administração na Universidade Federal da Bahia, em que eram analisadas as barreiras para a efetivação da gestão de conhecimento na Transpetro. Dentre as barreiras organizacionais identificadas, foi ressaltada a percepção dos entrevistados de que “Gestão de Conhecimento é modismo”. Para melhoria dessa barreira organizacional, é necessário que a empresa",
    options: ["técnica de grupo nominal", "reunião eletrônica", "brainstorming", "folga social", "groupthink"],
    correctIndex: 2,
    referenceAnswer: null,
    explanation: "Gabarito oficial Cesgranrio — Transpetro/PSP/TERRA/NÍVEL SUPERIOR 2023.2 (Administração). Fonte pública via PCI Concursos.",
  },
  {
    type: "MULTIPLE_CHOICE",
    subject: "Administração",
    prompt: "Para ajudar na orientação profissional de três colegas, um funcionário utilizou a escala de interesses vocacionais de Holland e identificou que: (i) o colega A tem habilidade atlética e mecânica, prefere trabalhar com atividades práticas, mão na massa, máquinas, ferramentas, ou trabalhar ao ar livre; (ii) o colega B gosta de desafios intelectuais, de observar, aprender, analisar, avaliar ou resolver problemas abstratos, é metódico e curioso acerca do mundo físico; e (iii) o colega C prefere atividades através das quais pode influenciar pessoas, liderando ou gerindo, visando a atingir metas. Com base nesse diagnóstico, o funcionário afirma que os três colegas ­— A, B e C — ­ se assemelham, at",
    options: ["convencional, artístico e social", "realista, investigativo e empreendedor", "perfeccionista, prestativo e bem-sucedido", "observador, romântico e questionador", "confrontador, sonhador e preservacionista U SC O H N A R 9 PROVA 1 - ADMINISTRAÇÃO www.pciconcursos.com.br pcimarkpci MjgwNDozZmJjOjBhODA6MTMwMDo1MDI0OjUwZmY6MjZiNTo2M2Y3:VHVlLCAwOCBTZXAgMjAyNiAxNTowMjoyNiAtMDMwMA== TRANSPETRO"],
    correctIndex: 1,
    referenceAnswer: null,
    explanation: "Gabarito oficial Cesgranrio — Transpetro/PSP/TERRA/NÍVEL SUPERIOR 2023.2 (Administração). Fonte pública via PCI Concursos.",
  },
  {
    type: "MULTIPLE_CHOICE",
    subject: "Administração",
    prompt: "Muito se tem discutido sobre as vantagens e desvantagens da verticalização do setor petrolífero. Uma empresa distribui, em média, 500 ventiladores por dia, com um desvio padrão de 100 unidades. O fornecedor entrega, em média, 500 ventiladores a cada 10 dias, com um desvio padrão de 2 dias. Essa empresa quer ter produtos em estoque para manter um nível de serviço de 95%. A empresa usa, como fórmula do estoque de segurança, a seguinte equação: SS = z x (mD x sL)2 + (mL x sD)2 Onde: • SS é o estoque de segurança; • z é o fator de segurança, que depende do nível de serviço desejado; • mD é a demanda média diária; • sD é o desvio padrão da demanda diária; • mL é o tempo médio de entrega; e • sL é",
    options: ["a firma pode crescer, mas a taxa de lucro diminui, já que não é possível a diminuição de custos devido a economias de escala e de escopo.", "há menor eficiência de produção, o que significa que há mais atrasos e erros à medida que os produtos trocam de mãos.", "diminui a capacidade da organização de acessar novos canais de distribuição, dificultando que a empresa alcance novos mercados.", "as empresas podem oferecer seus produtos a preços mais baixos, proporcionando um mercado mais competitivo para o consumidor.", "constrói-se uma forma de diversificação mais insegura diante das incertezas causadas por flutuações no mercado, o que dificulta o crescimento empresarial."],
    correctIndex: 2,
    referenceAnswer: null,
    explanation: "Gabarito oficial Cesgranrio — Transpetro/PSP/TERRA/NÍVEL SUPERIOR 2023.2 (Administração). Fonte pública via PCI Concursos.",
  },
  {
    type: "MULTIPLE_CHOICE",
    subject: "Administração",
    prompt: "Um contexto real em que essa liderança pode ser exercida ocorre quando um estaleiro Uma empresa produz e vende um produto que tem uma demanda anual de 12.000 unidades. O preço de venda do produto é de R$ 100,00 por unidade. O custo fixo anual da empresa com esse produto é de R$ 120.000,00 e o custo variável por unidade produzida é de R$ 60,00. Qual é o lucro anual (L), em R$, dessa empresa?",
    options: ["procura diferenciar a embarcação por ele construída em termos de qualidade, avanço tecnológico, preço, financiamento de custo mínimo e pontualidade na entrega, em relação à mesma embarcação construída por rivais.", "tem por objetivo empenhar-se para ser o detentor de baixo custo geral de construção de embarcações atraentes para uma grande faixa de armadores e para estaleiros que operam em larga escala de produção e competem globalmente.", "não baseia seu posicionamento de mercado em vantagens econômicas, mas sim na disposição do governo local ou nacional em querer proteger a sua indústria.", "se concentra num segmento de mercado mais estreito, ou seja, numa categoria de embarcação (ou embarcações) que seja(m) vendida(s) em nível mundial: altamente especializada(s), que requer(em) para sua construção um elevado padrão de mão de obra.", "foca a sua competitividade em um determinado país devido à influência de uma base de produção doméstica de aço e de componentes (navipeças e equipamentos), assim como pela existência abundante de mão de obra qualificada. PROVA 1 - ADMINISTRAÇÃO"],
    correctIndex: 1,
    referenceAnswer: null,
    explanation: "Gabarito oficial Cesgranrio — Transpetro/PSP/TERRA/NÍVEL SUPERIOR 2023.2 (Administração). Fonte pública via PCI Concursos.",
  },
  {
    type: "MULTIPLE_CHOICE",
    subject: "Administração",
    prompt: "O ciclo de vida de um projeto é composto por fases pelas quais um projeto passa, do seu início à sua conclusão. NÃO é pertinente às fases do ciclo de vida do projeto a seguinte característica:",
    options: ["terem custos semelhantes, independentemente do prazo definido do projeto.", "terem prazo definido, com um ponto de início, fim ou controle.", "terem um conjunto de atividades relacionadas de maneira lógica que culmina na conclusão de uma ou mais entregas.", "terem seus nomes, sua quantidade e sua duração determinados pelas necessidades de gerenciamento e controle das organizações envolvidas no projeto, pela natureza do projeto em si e pela sua área de aplicação.", "poderem ser sequenciais, iterativas ou sobrepostas."],
    correctIndex: 0,
    referenceAnswer: null,
    explanation: "Gabarito oficial Cesgranrio — Transpetro/PSP/TERRA/NÍVEL SUPERIOR 2023.2 (Administração). Fonte pública via PCI Concursos.",
  },
  {
    type: "MULTIPLE_CHOICE",
    subject: "Administração",
    prompt: "Um sistema de gerenciamento de armazéns (WMS) é um(a)",
    options: ["software para rastrear inventário.", "programa para gerenciar pedidos de compra.", "sistema para otimizar o fluxo de materiais e informações.", "solução para melhorar a eficiência do transporte.", "ferramenta para gerenciar a cadeia de suprimentos."],
    correctIndex: 2,
    referenceAnswer: null,
    explanation: "Gabarito oficial Cesgranrio — Transpetro/PSP/TERRA/NÍVEL SUPERIOR 2023.2 (Administração). Fonte pública via PCI Concursos.",
  },
  {
    type: "MULTIPLE_CHOICE",
    subject: "Administração",
    prompt: "O rastreamento dos produtos proporciona diversos benefícios à empresa, como o aumento na eficiência das entregas e dos serviços de campo. Uma tecnologia de rastreamento muito utilizada é a RFID, que faz o rastreamento dos produtos por",
    options: ["satélite", "radiofrequência", "ultrassom", "GPS", "bluetooth"],
    correctIndex: 1,
    referenceAnswer: null,
    explanation: "Gabarito oficial Cesgranrio — Transpetro/PSP/TERRA/NÍVEL SUPERIOR 2023.2 (Administração). Fonte pública via PCI Concursos.",
  },
  {
    type: "MULTIPLE_CHOICE",
    subject: "Administração",
    prompt: "Existem várias formas de identificação de produtos, dentre elas o código de barras, que é um sistema de identificação que consiste na",
    options: ["impressão gráfica de barras nas etiquetas ou nas próprias embalagens ou invólucros dos produtos.", "impressão gráfica de números nas etiquetas ou nas próprias embalagens ou invólucros dos produtos.", "impressão gráfica de letras nas etiquetas ou nas próprias embalagens ou invólucros dos produtos.", "impressão gráfica de figuras nas etiquetas ou nas próprias embalagens ou invólucros dos produtos.", "colagem de letras e de números nas etiquetas ou nas próprias embalagens ou invólucros dos produtos. TERRA"],
    correctIndex: 0,
    referenceAnswer: null,
    explanation: "Gabarito oficial Cesgranrio — Transpetro/PSP/TERRA/NÍVEL SUPERIOR 2023.2 (Administração). Fonte pública via PCI Concursos.",
  },
  {
    type: "MULTIPLE_CHOICE",
    subject: "Administração",
    prompt: "A gestão de compras é um processo fundamental para uma administração eficiente. De acordo com a visão moderna da administração, define-se compras como a atividade de adquirir bens e serviços que",
    options: ["500", "525", "600", "615", "700"],
    correctIndex: 4,
    referenceAnswer: null,
    explanation: "Gabarito oficial Cesgranrio — Transpetro/PSP/TERRA/NÍVEL SUPERIOR 2023.2 (Administração). Fonte pública via PCI Concursos.",
  },
  {
    type: "MULTIPLE_CHOICE",
    subject: "Administração",
    prompt: "Sobre os conceitos de programação para frente e programação para trás na produção, verifica-se que a programação para frente é uma técnica que visa",
    options: ["aumentar a flexibilidade e a customização, enquanto a programação para trás visa adaptar a produção à demanda dos clientes.", "diminuir o risco de erros e defeitos, enquanto a programação para trás visa otimizar o espaço físico e o layout.", "melhorar o fluxo de informações e o controle, enquanto a programação para trás visa integrar os fornecedores e os distribuidores.", "desenvolver as competências e as habilidades, enquanto a programação para trás visa reconhecer e recompensar os colaboradores.", "reduzir o prazo de entrega, enquanto a programação para trás visa produzir os bens para satisfazer a demanda existente, reduzindo custos de estoques e desequilíbrios entre oferta e demanda."],
    correctIndex: 4,
    referenceAnswer: null,
    explanation: "Gabarito oficial Cesgranrio — Transpetro/PSP/TERRA/NÍVEL SUPERIOR 2023.2 (Administração). Fonte pública via PCI Concursos.",
  },
  {
    type: "MULTIPLE_CHOICE",
    subject: "Administração",
    prompt: "Uma empresa monta bicicletas e tem uma previsão de demanda média mensal de 10.000 bicicletas para os próximos 3 meses. O custo médio de compras é de R$ 200,00, e cada unidade em estoque custa R$ 0,20. Os componentes que entram na montagem do produto seguem uma demanda determinista não variável no tempo, sem estoques de segurança. Nesse cenário, qual é a quantidade ótima de cada pedido de pedais para atender às previsões?",
    options: ["20.763", "15.280", "10.324", "8.944", "5.250"],
    correctIndex: 3,
    referenceAnswer: null,
    explanation: "Gabarito oficial Cesgranrio — Transpetro/PSP/TERRA/NÍVEL SUPERIOR 2023.2 (Administração). Fonte pública via PCI Concursos.",
  },
  {
    type: "MULTIPLE_CHOICE",
    subject: "Administração",
    prompt: "O padrão de relatório de sustentabilidade mais usado no mundo é o da GRI (Global Reporting Initiative), cujo objetivo é disseminar nas organizações a prática de medir o seu desempenho em termos ambientais, sociais e econômicos, divulgando os resultados como forma de prestação de contas à sociedade. As diretrizes para a elaboração de relatórios de sustentabilidade propostas pela GRI são formadas por duas categorias de princípios, que são:",
    options: ["Palmas", "Manaus", "Teresina", "Fortaleza", "Rio Branco"],
    correctIndex: 4,
    referenceAnswer: null,
    explanation: "Gabarito oficial Cesgranrio — Transpetro/PSP/TERRA/NÍVEL SUPERIOR 2023.2 (Administração). Fonte pública via PCI Concursos.",
  },
  {
    type: "MULTIPLE_CHOICE",
    subject: "Administração",
    prompt: "Um dos principais interesses da gestão ambiental é o entendimento a respeito do ciclo físico formado pelos sucessivos estágios do processo de produção e comercialização de um bem ou serviço. A realização da avaliação do ciclo de vida, conforme as normas ISO, requer equipe de trabalho multidisciplinar, leva tempo e pode custar muito caro. Isso faz com que pequenas e médias empresas realizem avaliações do ciclo de vida simplificadas, como a proposta no método Meco. Nesse método, as quatro categorias de impacto utilizadas são",
    options: ["transporte, entrega, compra e consumo", "disposição, supressão, carga e obtenção", "materiais, energia, substâncias químicas e outros", "minérios, eliminações, compósitos e orgânicos", "medições, exploração, concessão e descarte PROVA 1 - ADMINISTRAÇÃO Percentual de vendas da marca no Brasil"],
    correctIndex: 2,
    referenceAnswer: null,
    explanation: "Gabarito oficial Cesgranrio — Transpetro/PSP/TERRA/NÍVEL SUPERIOR 2023.2 (Administração). Fonte pública via PCI Concursos.",
  },
  {
    type: "MULTIPLE_CHOICE",
    subject: "Administração",
    prompt: "Uma ferramenta básica para a aplicação do conceito de desenvolvimento sustentável são os indicadores que permitem resumir as informações de caráter técnico e científico de fenômenos complexos e melhorar a comunicação e a gestão. De acordo com a classificação proposta em 1998 pela Organização para Cooperação e Desenvolvimento Econômico (OCDE), os indicadores ambientais são sistematizados pelo modelo PER. Esse modelo é formado por três grupos-chave de indicadores, denominados indicadores de",
    options: ["clientes", "investidores", "funcionários", "fornecedores", "meios de comunicação"],
    correctIndex: 4,
    referenceAnswer: null,
    explanation: "Gabarito oficial Cesgranrio — Transpetro/PSP/TERRA/NÍVEL SUPERIOR 2023.2 (Administração). Fonte pública via PCI Concursos.",
  },
  {
    type: "MULTIPLE_CHOICE",
    subject: "Administração",
    prompt: "Sempre que o gerente comercial da transportadora T vai apresentar os serviços da empresa a um novo cliente, ele reproduz um vídeo no qual os veículos da empresa são mostrados em detalhes e clientes atuais apresentam declarações a respeito dos serviços da empresa. Ele sabe que serviços não podem ser vistos, sentidos ou provados antes de serem contratados, o que está relacionado à característica diferenciadora dos serviços, denominada",
    options: ["variabilidade", "simultaneidade", "intangibilidade", "inseparabilidade", "heterogeneidade"],
    correctIndex: 2,
    referenceAnswer: null,
    explanation: "Gabarito oficial Cesgranrio — Transpetro/PSP/TERRA/NÍVEL SUPERIOR 2023.2 (Administração). Fonte pública via PCI Concursos.",
  },
  {
    type: "MULTIPLE_CHOICE",
    subject: "Administração",
    prompt: "Um levantamento realizado pela direção da empresa W Transportes mostrou que o ciclo de vida médio dos clientes corporativos de serviços de transportes é de 6 anos. Se o objetivo da direção é que o valor da relação comercial de cada cliente corporativo seja, no mínimo, de R$ 300.000,00, qual deve ser o montante mínimo de negócios mensais de cada cliente da empresa? A campanha promocional da empresa de transportes W traz um famoso ator de TV, que já recebeu muitos prêmios e tem uma carreira consolidada, como garoto-propaganda. Sabe-se que o comportamento do consumidor é influenciado por grupos de referência. Nesse contexto, o ator é utilizado na propaganda porque faz parte do grupo de referênc",
    options: ["preço", "consulta", "transação", "valor estratégico", "solução de vendas TERRA"],
    correctIndex: 0,
    referenceAnswer: null,
    explanation: "Gabarito oficial Cesgranrio — Transpetro/PSP/TERRA/NÍVEL SUPERIOR 2023.2 (Administração). Fonte pública via PCI Concursos.",
  },
  {
    type: "MULTIPLE_CHOICE",
    subject: "Administração",
    prompt: "O planejamento de marketing envolve a análise do mercado, incluindo as preferências dos consumidores e a força dos concorrentes. A empresa T, que atua no setor alimentício, contratou um instituto de pesquisa de mercado, que entrevistou dois mil consumidores ao longo de uma semana. O resumo dos resultados é apresentado no Quadro a seguir: Empresa T Y W A empresa Z é uma tradicional transportadora marítima de cargas, atuando há mais de quarenta anos sob a marca Z Transportes. Na reunião mais recente, o conselho da empresa apontou que era necessário que a empresa aumentasse suas receitas de vendas e propôs que passasse a vender roupas baseadas nos uniformes utilizados pelos trabalhadores da emp",
    options: ["linha", "categoria", "segmento", "visibilidade", "representação Com base nesses dados e considerando-se que cada consumidor mencionou apenas um nome para cada uma das peguntas, verifica-se que o share-of-mind da empresa T é de"],
    correctIndex: 1,
    referenceAnswer: null,
    explanation: "Gabarito oficial Cesgranrio — Transpetro/PSP/TERRA/NÍVEL SUPERIOR 2023.2 (Administração). Fonte pública via PCI Concursos.",
  },
  {
    type: "MULTIPLE_CHOICE",
    subject: "Administração",
    prompt: "O gerenciamento das aquisições do projeto inclui os processos necessários para comprar ou adquirir produtos, serviços ou resultados externos à equipe do projeto. NÃO é próprio do gerenciamento das aquisições do projeto",
    options: ["dispensa de licitação", "inexigibilidade do certame", "suspensão da compra", "diminuição dos preços", "negociação livre"],
    correctIndex: 3,
    referenceAnswer: null,
    explanation: "Gabarito oficial Cesgranrio — Transpetro/PSP/TERRA/NÍVEL SUPERIOR 2023.2 (Administração). Fonte pública via PCI Concursos.",
  },
  {
    type: "MULTIPLE_CHOICE",
    subject: "Administração",
    prompt: "Se o endividamento de longo prazo de uma empresa é destinado a financiar seu capital de giro líquido, um índice cuja razão entre exigíveis (curto e longo prazo) e capital de giro líquido seja igual a 1 significa que a(o)",
    options: ["empresa mantém um capital de giro líquido abaixo do volume de dívidas de longo prazo.", "empresa mantém um capital de giro líquido igual ao volume de dívidas de curto prazo.", "empresa fez uma captação de recursos de terceiros de longo prazo para financiar o ativo não circulante.", "ativo circulante da empresa não é suficiente para quitar as dívidas totais.", "patrimônio líquido está aplicado em ativo não circulante."],
    correctIndex: 4,
    referenceAnswer: null,
    explanation: "Gabarito oficial Cesgranrio — Transpetro/PSP/TERRA/NÍVEL SUPERIOR 2023.2 (Administração). Fonte pública via PCI Concursos.",
  },
];

