// Concept: Subject lexicon (§15.5) — canonical concurso subjects, their aliases
// as editais write them, and the conventional topic grouping used by the
// syllabus residue prompt and the study UI.
//
// Data lives in TypeScript rather than YAML so it ships inside the compiled
// package (web + workers) without runtime file IO. The shape mirrors the YAML
// proposed in the spec one-to-one.

export interface CanonicalSubject {
  /** Stable slug id; the canonical key prefix for cross-exam reuse. */
  id: string;
  canonical: string;
  aliases: readonly string[];
  conventionalTopics: readonly string[];
  /** Subject family; `legal` subjects route norm references to direct-mode sources. */
  family: "language" | "math" | "it" | "legal" | "admin" | "finance" | "health" | "engineering" | "general";
}

export const CANONICAL_SUBJECTS: readonly CanonicalSubject[] = [
  {
    id: "lingua-portuguesa",
    canonical: "Língua Portuguesa",
    aliases: ["Português", "Portugues", "Língua Portuguesa e Interpretação de Texto", "Comunicação Oficial", "Gramática", "Redação Oficial", "Português Instrumental", "Língua Portuguesa e Redação Oficial", "Interpretação de Texto"],
    conventionalTopics: ["Interpretação de texto", "Ortografia", "Acentuação", "Morfologia", "Sintaxe", "Concordância", "Regência", "Crase", "Pontuação", "Semântica", "Redação oficial"],
    family: "language",
  },
  {
    id: "raciocinio-logico",
    canonical: "Raciocínio Lógico",
    aliases: ["Raciocínio Lógico-Matemático", "Raciocínio Lógico Matemático", "Lógica", "Matemática e Raciocínio Lógico", "Raciocínio Lógico e Matemático", "Raciocínio Lógico Quantitativo", "Lógica Matemática"],
    conventionalTopics: ["Proposições", "Conectivos", "Tabelas-verdade", "Equivalências", "Argumentos", "Análise combinatória", "Probabilidade", "Sequências", "Diagramas lógicos"],
    family: "math",
  },
  {
    id: "matematica",
    canonical: "Matemática",
    aliases: ["Matemática Básica", "Matemática Financeira", "Noções de Matemática", "Matemática Aplicada"],
    conventionalTopics: ["Conjuntos numéricos", "Porcentagem", "Razão e proporção", "Regra de três", "Juros simples e compostos", "Funções", "Equações", "Geometria", "Estatística básica"],
    family: "math",
  },
  {
    id: "nocoes-de-informatica",
    canonical: "Noções de Informática",
    aliases: ["Informática", "Tecnologia da Informação Básica", "Informática Básica", "Conhecimentos de Informática", "Noções de Tecnologia da Informação"],
    conventionalTopics: ["Sistemas operacionais", "Editores de texto", "Planilhas", "Internet e correio eletrônico", "Segurança da informação", "Redes", "Hardware e software"],
    family: "it",
  },
  {
    id: "tecnologia-da-informacao",
    canonical: "Tecnologia da Informação",
    aliases: ["TI", "Informática Avançada", "Sistemas de Informação", "Engenharia de Software", "Análise de Sistemas", "Desenvolvimento de Sistemas"],
    conventionalTopics: ["Bancos de dados", "Redes de computadores", "Segurança da informação", "Engenharia de software", "Programação", "Governança de TI", "Arquitetura de sistemas"],
    family: "it",
  },
  {
    id: "direito-constitucional",
    canonical: "Direito Constitucional",
    aliases: ["Noções de Direito Constitucional", "Constituição Federal", "Constitucional"],
    conventionalTopics: ["Princípios fundamentais", "Direitos e garantias fundamentais", "Organização do Estado", "Organização dos Poderes", "Controle de constitucionalidade", "Administração Pública na CF", "Ordem social"],
    family: "legal",
  },
  {
    id: "direito-administrativo",
    canonical: "Direito Administrativo",
    aliases: ["Noções de Direito Administrativo", "Administrativo", "Direito Administrativo e Constitucional"],
    conventionalTopics: ["Princípios da Administração Pública", "Atos administrativos", "Poderes administrativos", "Licitações", "Contratos administrativos", "Servidores públicos", "Responsabilidade civil do Estado", "Improbidade administrativa", "Processo administrativo"],
    family: "legal",
  },
  {
    id: "administracao-publica",
    canonical: "Administração Pública",
    aliases: ["Noções de Administração Pública", "Gestão Pública", "Administração Geral e Pública"],
    conventionalTopics: ["Modelos de administração", "Governança pública", "Orçamento público", "Planejamento", "Controle", "Ética no serviço público"],
    family: "admin",
  },
  {
    id: "administracao-geral",
    canonical: "Administração Geral",
    aliases: ["Administração", "Noções de Administração", "Teoria Geral da Administração", "Administração de Empresas"],
    conventionalTopics: ["Funções administrativas", "Planejamento estratégico", "Estrutura organizacional", "Gestão de pessoas", "Gestão da qualidade", "Processos"],
    family: "admin",
  },
  {
    id: "atualidades",
    canonical: "Atualidades",
    aliases: ["Conhecimentos Gerais", "Atualidades e Conhecimentos Gerais", "Realidade Brasileira"],
    conventionalTopics: ["Política", "Economia", "Sociedade", "Meio ambiente", "Ciência e tecnologia"],
    family: "general",
  },
  {
    id: "legislacao-especifica",
    canonical: "Legislação Específica",
    aliases: ["Legislação", "Legislação Institucional", "Legislação Aplicada", "Legislação Pertinente", "Lei Orgânica"],
    conventionalTopics: ["Lei orgânica", "Regimento interno", "Estatuto dos servidores", "Legislação do órgão"],
    family: "legal",
  },
  {
    id: "contabilidade-geral",
    canonical: "Contabilidade Geral",
    aliases: ["Contabilidade", "Noções de Contabilidade", "Contabilidade Básica", "Ciências Contábeis"],
    conventionalTopics: ["Patrimônio", "Plano de contas", "Demonstrações contábeis", "Balanço patrimonial", "DRE", "Lançamentos", "Provisões"],
    family: "finance",
  },
  {
    id: "contabilidade-publica",
    canonical: "Contabilidade Pública",
    aliases: ["Contabilidade Aplicada ao Setor Público", "CASP", "Contabilidade Governamental"],
    conventionalTopics: ["MCASP", "Receita pública", "Despesa pública", "Demonstrações do setor público", "Plano de contas aplicado ao setor público"],
    family: "finance",
  },
  {
    id: "auditoria",
    canonical: "Auditoria",
    aliases: ["Auditoria Governamental", "Auditoria Interna", "Auditoria Contábil", "Noções de Auditoria"],
    conventionalTopics: ["Normas de auditoria", "Planejamento de auditoria", "Evidências", "Relatórios", "Controle interno", "Amostragem"],
    family: "finance",
  },
  {
    id: "controle-externo",
    canonical: "Controle Externo",
    aliases: ["Controle Externo e Interno", "Controle da Administração Pública", "Noções de Controle Externo"],
    conventionalTopics: ["Tribunais de Contas", "Competências constitucionais", "Fiscalização", "Auditoria", "Inspeção", "Levantamento", "Tomada de contas"],
    family: "legal",
  },
  {
    id: "afo",
    canonical: "Administração Financeira e Orçamentária",
    aliases: ["AFO", "Orçamento Público", "Finanças Públicas", "Administração Orçamentária e Financeira", "Direito Financeiro"],
    conventionalTopics: ["PPA", "LDO", "LOA", "Receita e despesa", "Ciclo orçamentário", "Lei 4.320/64", "LRF", "Créditos adicionais"],
    family: "finance",
  },
  {
    id: "direito-tributario",
    canonical: "Direito Tributário",
    aliases: ["Legislação Tributária", "Tributário", "Noções de Direito Tributário"],
    conventionalTopics: ["Sistema tributário nacional", "Competência tributária", "Obrigação tributária", "Crédito tributário", "Impostos", "Taxas", "Contribuições"],
    family: "legal",
  },
  {
    id: "direito-civil",
    canonical: "Direito Civil",
    aliases: ["Noções de Direito Civil", "Civil"],
    conventionalTopics: ["Pessoas", "Bens", "Fatos jurídicos", "Obrigações", "Contratos", "Responsabilidade civil", "Família", "Sucessões"],
    family: "legal",
  },
  {
    id: "direito-processual-civil",
    canonical: "Direito Processual Civil",
    aliases: ["Processo Civil", "Processual Civil", "Noções de Direito Processual Civil"],
    conventionalTopics: ["Jurisdição e ação", "Partes e procuradores", "Atos processuais", "Procedimento comum", "Recursos", "Execução", "Tutela provisória"],
    family: "legal",
  },
  {
    id: "direito-penal",
    canonical: "Direito Penal",
    aliases: ["Noções de Direito Penal", "Penal"],
    conventionalTopics: ["Princípios", "Aplicação da lei penal", "Crime", "Imputabilidade", "Concurso de pessoas", "Penas", "Crimes contra a administração pública"],
    family: "legal",
  },
  {
    id: "direito-processual-penal",
    canonical: "Direito Processual Penal",
    aliases: ["Processo Penal", "Processual Penal", "Noções de Direito Processual Penal"],
    conventionalTopics: ["Inquérito policial", "Ação penal", "Provas", "Prisões", "Procedimentos", "Recursos", "Habeas corpus"],
    family: "legal",
  },
  {
    id: "direito-do-trabalho",
    canonical: "Direito do Trabalho",
    aliases: ["Legislação Trabalhista", "Trabalhista", "Noções de Direito do Trabalho", "CLT"],
    conventionalTopics: ["Relação de emprego", "Contrato de trabalho", "Jornada", "Remuneração", "Férias", "FGTS", "Rescisão", "Direito coletivo"],
    family: "legal",
  },
  {
    id: "direito-processual-do-trabalho",
    canonical: "Direito Processual do Trabalho",
    aliases: ["Processo do Trabalho", "Processual do Trabalho"],
    conventionalTopics: ["Justiça do Trabalho", "Dissídios", "Recursos trabalhistas", "Execução trabalhista"],
    family: "legal",
  },
  {
    id: "direito-previdenciario",
    canonical: "Direito Previdenciário",
    aliases: ["Legislação Previdenciária", "Previdenciário", "Seguridade Social", "Noções de Direito Previdenciário"],
    conventionalTopics: ["Seguridade social", "Regime geral", "Beneficiários", "Benefícios", "Custeio", "Regimes próprios"],
    family: "legal",
  },
  {
    id: "direito-empresarial",
    canonical: "Direito Empresarial",
    aliases: ["Direito Comercial", "Empresarial"],
    conventionalTopics: ["Empresário", "Sociedades", "Títulos de crédito", "Falência e recuperação", "Contratos empresariais"],
    family: "legal",
  },
  {
    id: "direito-ambiental",
    canonical: "Direito Ambiental",
    aliases: ["Legislação Ambiental", "Ambiental"],
    conventionalTopics: ["Princípios", "Política Nacional do Meio Ambiente", "Licenciamento", "Responsabilidade ambiental", "Unidades de conservação"],
    family: "legal",
  },
  {
    id: "direito-eleitoral",
    canonical: "Direito Eleitoral",
    aliases: ["Legislação Eleitoral", "Eleitoral"],
    conventionalTopics: ["Justiça Eleitoral", "Direitos políticos", "Partidos", "Eleições", "Propaganda", "Crimes eleitorais"],
    family: "legal",
  },
  {
    id: "direitos-humanos",
    canonical: "Direitos Humanos",
    aliases: ["Direitos Humanos e Cidadania", "Noções de Direitos Humanos"],
    conventionalTopics: ["Declaração Universal", "Sistema interamericano", "Tratados", "Grupos vulneráveis"],
    family: "legal",
  },
  {
    id: "etica-no-servico-publico",
    canonical: "Ética no Serviço Público",
    aliases: ["Ética", "Ética Profissional", "Ética na Administração Pública", "Ética e Conduta"],
    conventionalTopics: ["Ética e moral", "Código de ética", "Conflito de interesses", "Improbidade", "Transparência"],
    family: "admin",
  },
  {
    id: "economia",
    canonical: "Economia",
    aliases: ["Noções de Economia", "Economia Brasileira", "Macroeconomia", "Microeconomia", "Ciências Econômicas"],
    conventionalTopics: ["Microeconomia", "Macroeconomia", "Inflação", "Política monetária", "Política fiscal", "Setor externo"],
    family: "finance",
  },
  {
    id: "estatistica",
    canonical: "Estatística",
    aliases: ["Noções de Estatística", "Estatística Básica", "Estatística Aplicada"],
    conventionalTopics: ["Medidas de tendência central", "Dispersão", "Probabilidade", "Distribuições", "Amostragem", "Inferência", "Regressão"],
    family: "math",
  },
  {
    id: "arquivologia",
    canonical: "Arquivologia",
    aliases: ["Noções de Arquivologia", "Gestão de Documentos", "Arquivística"],
    conventionalTopics: ["Gestão de documentos", "Classificação", "Tabela de temporalidade", "Protocolo", "Preservação"],
    family: "admin",
  },
  {
    id: "gestao-de-pessoas",
    canonical: "Gestão de Pessoas",
    aliases: ["Recursos Humanos", "Administração de Recursos Humanos", "Gestão de RH"],
    conventionalTopics: ["Recrutamento e seleção", "Treinamento", "Avaliação de desempenho", "Liderança", "Motivação", "Cultura organizacional"],
    family: "admin",
  },
  {
    id: "gestao-de-projetos",
    canonical: "Gestão de Projetos",
    aliases: ["Gerenciamento de Projetos", "Projetos"],
    conventionalTopics: ["Ciclo de vida", "Escopo", "Cronograma", "Riscos", "PMBOK", "Metodologias ágeis"],
    family: "admin",
  },
  {
    id: "gestao-de-processos",
    canonical: "Gestão de Processos",
    aliases: ["Gerenciamento de Processos", "BPM", "Mapeamento de Processos"],
    conventionalTopics: ["Mapeamento", "Modelagem", "BPMN", "Indicadores", "Melhoria contínua"],
    family: "admin",
  },
  {
    id: "seguranca-da-informacao",
    canonical: "Segurança da Informação",
    aliases: ["Segurança de Redes", "Segurança Cibernética", "Cibersegurança"],
    conventionalTopics: ["Criptografia", "Autenticação", "Malware", "Políticas de segurança", "Normas ISO 27001", "LGPD"],
    family: "it",
  },
  {
    id: "banco-de-dados",
    canonical: "Banco de Dados",
    aliases: ["Bancos de Dados", "SGBD", "Modelagem de Dados"],
    conventionalTopics: ["Modelo relacional", "SQL", "Normalização", "Transações", "Índices", "NoSQL"],
    family: "it",
  },
  {
    id: "redes-de-computadores",
    canonical: "Redes de Computadores",
    aliases: ["Redes", "Infraestrutura de Redes", "Telecomunicações"],
    conventionalTopics: ["Modelo OSI", "TCP/IP", "Roteamento", "Endereçamento IP", "Protocolos", "Redes sem fio"],
    family: "it",
  },
  {
    id: "programacao",
    canonical: "Programação",
    aliases: ["Linguagens de Programação", "Desenvolvimento de Software", "Lógica de Programação", "Algoritmos"],
    conventionalTopics: ["Algoritmos", "Estruturas de dados", "Orientação a objetos", "Java", "Python", "JavaScript", "Testes"],
    family: "it",
  },
  {
    id: "governanca-de-ti",
    canonical: "Governança de TI",
    aliases: ["Gestão de TI", "ITIL", "COBIT"],
    conventionalTopics: ["ITIL", "COBIT", "Gestão de serviços", "Contratações de TI"],
    family: "it",
  },
  {
    id: "engenharia-civil",
    canonical: "Engenharia Civil",
    aliases: ["Construção Civil", "Engenharia de Estruturas"],
    conventionalTopics: ["Estruturas", "Materiais", "Geotecnia", "Hidráulica", "Planejamento de obras", "Orçamento de obras"],
    family: "engineering",
  },
  {
    id: "engenharia-eletrica",
    canonical: "Engenharia Elétrica",
    aliases: ["Eletricidade", "Eletrotécnica", "Sistemas Elétricos"],
    conventionalTopics: ["Circuitos", "Máquinas elétricas", "Sistemas de potência", "Instalações elétricas", "Eletrônica"],
    family: "engineering",
  },
  {
    id: "engenharia-mecanica",
    canonical: "Engenharia Mecânica",
    aliases: ["Mecânica", "Manutenção Mecânica"],
    conventionalTopics: ["Termodinâmica", "Mecânica dos fluidos", "Resistência dos materiais", "Manutenção", "Máquinas"],
    family: "engineering",
  },
  {
    id: "seguranca-do-trabalho",
    canonical: "Segurança do Trabalho",
    aliases: ["Saúde e Segurança do Trabalho", "Engenharia de Segurança do Trabalho", "SST", "Normas Regulamentadoras"],
    conventionalTopics: ["Normas regulamentadoras", "EPI e EPC", "Riscos ocupacionais", "CIPA", "Prevenção de acidentes"],
    family: "engineering",
  },
  {
    id: "enfermagem",
    canonical: "Enfermagem",
    aliases: ["Técnico de Enfermagem", "Enfermagem Geral"],
    conventionalTopics: ["Fundamentos de enfermagem", "Farmacologia", "Saúde pública", "Ética profissional", "Biossegurança", "Urgência e emergência"],
    family: "health",
  },
  {
    id: "saude-publica",
    canonical: "Saúde Pública",
    aliases: ["Legislação do SUS", "SUS", "Sistema Único de Saúde", "Políticas de Saúde", "Saúde Coletiva"],
    conventionalTopics: ["Lei 8.080/90", "Lei 8.142/90", "Princípios do SUS", "Atenção básica", "Vigilância em saúde", "Epidemiologia"],
    family: "health",
  },
  {
    id: "medicina",
    canonical: "Medicina",
    aliases: ["Clínica Médica", "Conhecimentos Médicos"],
    conventionalTopics: ["Clínica médica", "Emergências", "Farmacologia", "Semiologia"],
    family: "health",
  },
  {
    id: "psicologia",
    canonical: "Psicologia",
    aliases: ["Psicologia Organizacional", "Psicologia Geral"],
    conventionalTopics: ["Avaliação psicológica", "Psicologia organizacional", "Ética profissional", "Teorias da personalidade"],
    family: "health",
  },
  {
    id: "servico-social",
    canonical: "Serviço Social",
    aliases: ["Assistência Social", "Política de Assistência Social"],
    conventionalTopics: ["Política de assistência social", "SUAS", "Ética profissional", "Instrumentais técnicos"],
    family: "health",
  },
  {
    id: "pedagogia",
    canonical: "Pedagogia",
    aliases: ["Conhecimentos Pedagógicos", "Fundamentos da Educação", "Legislação Educacional", "Didática", "Educação"],
    conventionalTopics: ["LDB", "Currículo", "Avaliação", "Didática", "Teorias da aprendizagem", "Gestão escolar"],
    family: "general",
  },
  {
    id: "historia",
    canonical: "História",
    aliases: ["História do Brasil", "História Geral", "História e Geografia"],
    conventionalTopics: ["Brasil Colônia", "Império", "República", "História contemporânea"],
    family: "general",
  },
  {
    id: "geografia",
    canonical: "Geografia",
    aliases: ["Geografia do Brasil", "Geografia Geral", "Geografia Regional"],
    conventionalTopics: ["Geografia física", "Geografia humana", "Regionalização", "Urbanização", "Meio ambiente"],
    family: "general",
  },
  {
    id: "lingua-inglesa",
    canonical: "Língua Inglesa",
    aliases: ["Inglês", "Ingles", "Inglês Técnico", "Inglês Instrumental"],
    conventionalTopics: ["Reading comprehension", "Vocabulary", "Grammar", "Text structure"],
    family: "language",
  },
  {
    id: "lingua-espanhola",
    canonical: "Língua Espanhola",
    aliases: ["Espanhol", "Espanhol Instrumental"],
    conventionalTopics: ["Compreensão de texto", "Vocabulário", "Gramática"],
    family: "language",
  },
  {
    id: "fisica",
    canonical: "Física",
    aliases: ["Física Geral", "Física Aplicada"],
    conventionalTopics: ["Mecânica", "Termologia", "Óptica", "Eletricidade", "Ondulatória"],
    family: "math",
  },
  {
    id: "quimica",
    canonical: "Química",
    aliases: ["Química Geral", "Química Aplicada"],
    conventionalTopics: ["Química geral", "Química orgânica", "Química inorgânica", "Físico-química"],
    family: "math",
  },
  {
    id: "biologia",
    canonical: "Biologia",
    aliases: ["Ciências Biológicas", "Ciências"],
    conventionalTopics: ["Citologia", "Genética", "Ecologia", "Fisiologia", "Evolução"],
    family: "health",
  },
  {
    id: "seguranca-publica",
    canonical: "Segurança Pública",
    aliases: ["Noções de Segurança Pública", "Legislação de Trânsito", "Trânsito", "Criminologia"],
    conventionalTopics: ["Sistema de segurança pública", "Legislação de trânsito", "Criminologia", "Direitos humanos aplicados"],
    family: "legal",
  },
  {
    id: "licitacoes-e-contratos",
    canonical: "Licitações e Contratos",
    aliases: ["Licitações", "Lei de Licitações", "Lei 14.133", "Compras Públicas", "Contratações Públicas"],
    conventionalTopics: ["Modalidades", "Fases da licitação", "Contratação direta", "Contratos administrativos", "Sanções"],
    family: "legal",
  },
  {
    id: "conhecimentos-bancarios",
    canonical: "Conhecimentos Bancários",
    aliases: ["Sistema Financeiro Nacional", "Mercado Financeiro", "Produtos Bancários", "Noções de Mercado Financeiro"],
    conventionalTopics: ["Sistema Financeiro Nacional", "Produtos e serviços bancários", "Mercado de capitais", "Garantias", "Prevenção à lavagem de dinheiro"],
    family: "finance",
  },
  {
    id: "vendas-e-negociacao",
    canonical: "Vendas e Negociação",
    aliases: ["Técnicas de Vendas", "Atendimento ao Cliente", "Atendimento", "Negociação", "Marketing"],
    conventionalTopics: ["Atendimento", "Negociação", "Marketing de relacionamento", "Ética em vendas", "Código de defesa do consumidor"],
    family: "admin",
  },
  {
    id: "logistica",
    canonical: "Logística",
    aliases: ["Administração de Materiais", "Gestão de Suprimentos", "Cadeia de Suprimentos", "Gestão de Estoques"],
    conventionalTopics: ["Gestão de estoques", "Compras", "Armazenagem", "Transporte", "Cadeia de suprimentos"],
    family: "admin",
  },
  {
    id: "conhecimentos-especificos",
    canonical: "Conhecimentos Específicos",
    aliases: ["Específicos", "Conhecimentos Específicos do Cargo"],
    conventionalTopics: [],
    family: "general",
  },
];

export const LEGAL_SUBJECT_IDS: ReadonlySet<string> = new Set(
  CANONICAL_SUBJECTS.filter((s) => s.family === "legal").map((s) => s.id),
);
